builders:
  stackedRouterGenerator:
    import: "package:stacked_app_generator/builder.dart"
    builder_factories: ["stackedRouterGenerator"]
    build_extensions: {'.dart': ['.gr.dart']}
    auto_apply: dependents
    build_to: source
