name: FilledStacks
repository: https://github.com/FilledStacks/stacked

packages:
  - packages/stacked/**
  - packages/stacked_crashlytics/**
  - packages/stacked_firebase_auth/**
  - packages/stacked_generator/**
  - packages/stacked_gql/**
  - packages/stacked_hooks/**
  # - packages/stacked_localisation/**
  - packages/stacked_services/**
  - packages/stacked_themes/**

ignore:
  - packages/stacked_generator/test/**/integration_test/**

command:
  version:
    # Generate commit links in package changelogs.
    linkToCommits: true
    # Only allow versioning to happen on main branch.
    branch: master
    # Additionally build a changelog at the root of the workspace.
    workspaceChangelog: true

scripts:
  pub_get:
    run: |
      melos exec \
      -c 8 \
      --fail-fast \
      -- \
        "flutter pub get"
    description: |
      Install Flutter dependencies
  pub_upgrade:
    run: |
      melos exec \
      -c 8 \
      --fail-fast \
      -- \
        "flutter pub upgrade"
    description: |
      Upgrade Flutter dependencies
  build:
    run: |
        melos exec \
        -c 8 \
        --fail-fast \
        -- \
          "if grep -q build_runner "pubspec.yaml"; then
              flutter pub run build_runner build --delete-conflicting-outputs  && exit
          fi"
    description: |
      Execute "build_runner build" to every Flutter project and packages under the monorepo.
  test:
    run: |
      melos exec \
        -c 8 \
        --fail-fast \
        --ignore "*stacked_localisation*" \
        --ignore "*stacked_tools/playground" \
        -- \
          "if grep -q flutter "pubspec.yaml"; then
            flutter test
          elif [ -d "test" ]; then
            dart test
          fi"
    description: |
      Execute test on every project.
  # Additional cleanup lifecycle script, executed when `melos clean` is run.
  postclean: >
    melos exec -c 6 -- "flutter clean"
