name: stacked_app
description: Stacked App is a package dedicated to reducing the boiler plate required for a stacked application
version: 0.1.0
homepage: https://github.com/Milad-Akarie/auto_route_library

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8
dev_dependecies:
  flutter_test:
    sdk: flutter
  test:

