builders:
  stackedRouterGenerator:
    import: "package:stacked_generator/builder.dart"
    builder_factories: ["stackedRouterGenerator"]
    build_extensions: { ".dart": [".router.dart"] }
    auto_apply: dependents
    build_to: source

  # stackedLocatorGenerator:
  #   import: "package:stacked_generator/builder.dart"
  #   builder_factories: ["stackedLocatorGenerator"]
  #   build_extensions: { ".dart": [".locator.dart"] }
  #   auto_apply: dependents
  #   build_to: source
