name: Stacked App Integration Tests

on: [push, pull_request]

jobs:
  integration_tests:
    runs-on: ubuntu-latest


env:
  flutter_channel: "stable"

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ env.flutter_channel }}

      - uses: actions/checkout@v2
      - uses: nanasess/setup-chromedriver@v1
        with:
          chromedriver_version: "102.0.5005.61"
      - run: flutter pub get
      - run: chromedriver --port=4444 &
      - run: cd packages/stacked/example
      - run: |
          flutter drive \
            --driver=test_driver/integration_test.dart \
            --target=integration_test/app_test.dart \
            -d web-server
