name: Stacked App Integration Tests

on: [push, pull_request]

jobs:
  integration_tests:
    name: Run stacked app integration tests
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Setup chrome driver
        uses: nanasess/setup-chromedriver@v1
        with:
          chromedriver_version: "102.0.5005.61"

      - name: Install dependencies
        run: flutter pub get

      - name: Run integration tests
        run: cd packages/stacked/example
      - run: chromedriver --port=4444 &
      - run: |
          flutter drive \
            --driver=test_driver/integration_test.dart \
            --target=integration_test/app_test.dart \
            -d web-server
